services:

  postgres:
    image: postgres:17

    container_name: infrastack-postgres

    environment:
      POSTGRES_DB: infrastack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: skai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: